### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by lambtron** [mootcycle/slackporter#1]
just wondering, i am running this locally, but i get this error:

```
🍉 🍉 🍉  slackporter (master): node index.js
info:

Server running at: http://127.0.0.1:2603
info: getLoginPage for:  127.0.0.1  --  https://segmentio.slack.com
info: getLoginPage for:  127.0.0.1  --  https://20percent.slack.com
info: postLoginPage for:  127.0.0.1  --  https://segmentio.slack.com
info: postLoginPage for:  127.0.0.1  --  https://20percent.slack.com
error: emojilist all handler Error:
[TypeError: Cannot read property 'hasOwnProperty' of undefined]
Debug: internal, implementation, error
    Error: Internal Server Error
    at Object.exports.create (/Users/andyjiang/Developer/slackporter/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/andyjiang/Developer/slackporter/node_modules/boom/lib/index.js:254:99)
    at Object.exports.badImplementation (/Users/andyjiang/Developer/slackporter/node_modules/boom/lib/index.js:290:23)
    at /Users/andyjiang/Developer/slackporter/index.js:121:20
    at _rejected (/Users/andyjiang/Developer/slackporter/node_modules/q/q.js:844:24)
    at /Users/andyjiang/Developer/slackporter/node_modules/q/q.js:870:30
    at Promise.when (/Users/andyjiang/Developer/slackporter/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/andyjiang/Developer/slackporter/node_modules/q/q.js:788:41)
    at /Users/andyjiang/Developer/slackporter/node_modules/q/q.js:604:44
    at runSingle (/Users/andyjiang/Developer/slackporter/node_modules/q/q.js:137:13)
```

Any env variables I need to set or anything?

Thank you!

**Comment by mootcycle** [comment]
Hey, I just tested things on my local machine and it's still working properly for me. I did notice that while https://segmentio.slack.com/ does load the standard slack team login page, https://20percent.slack.com gives me a 404 error. Is that the right team name? I updated the repo with a better error message for you. Let me know if this helps. Thanks for the interest!

**Comment by lambtron** [comment]
wow you are so right. i updated the URL and it still didn't work, but i think i now know the reason. i have TFA turned on for the "from" account, which probably prevents the script from signing into the page.

thank you so much for your contributions!!
