### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nicoszerman** [mootcycle/slackporter#4]
When using the tool, and correctly putting everything (checked by logging in), an error message with "internal server error" appears.

**Comment by ryangiglio** [comment]
Same.

Additionally, on the node command line I get this error

```
error: emojilist all handler Error:
[TypeError: The header content contains invalid characters]
Debug: internal, implementation, error
    Error: Internal Server Error
    at /Users/rgiglio/Development/slackporter/index.js:128:20
    at _rejected (/Users/rgiglio/Development/slackporter/node_modules/q/q.js:844:24)
    at /Users/rgiglio/Development/slackporter/node_modules/q/q.js:870:30
    at Promise.when (/Users/rgiglio/Development/slackporter/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/rgiglio/Development/slackporter/node_modules/q/q.js:788:41)
    at /Users/rgiglio/Development/slackporter/node_modules/q/q.js:604:44
    at runSingle (/Users/rgiglio/Development/slackporter/node_modules/q/q.js:137:13)
    at flush (/Users/rgiglio/Development/slackporter/node_modules/q/q.js:125:13)
    at _combinedTickCallback (node.js:370:9)
    at process._tickDomainCallback (node.js:425:11)
```

**Comment by Seluj78** [comment]
Anybody got a solution to this ? I have this error on window and mac...

**Comment by giftig** [comment]
Same problem here; same error as ryangiglio. Looks like they've updated something and this project is behind.

**Comment by asanakoy** [comment]
any updates?

**Comment by giftig** [comment]
Looks like this project isn't supported; last commit was 2 years ago. Someone else will have to pick up the reins if they want it, I guess. Personally I solved my problem by eliminating the need to use more than one slack team.

**Comment by mootcycle** [comment]
My apologies. I'd left this thing fallow for a while. I just fixed a bunch of stuff and it should work again with `node.js` v6+.

**Comment by clarencestephen** [comment]
I got an error when clicking on emoji's i wanted to transfer.
